[package]
name = "raytracer"
version = "0.1.0"
authors = ["maxkl <max@maxkl.de>"]
edition = "2018"

[dependencies]
image = "0.21.1"
cgmath = { version = "0.17.0", features = ["serde"] }
serde = { version = "1.0.91", features = ["derive"] }
typetag = "0.1.2"
ron = "0.5.1"
